name: Package addon

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q

      - name: Package Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Package BCC
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Retail
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
